/*//////////////////////////////////////////////////////////////////
////     The SKIRT project -- advanced radiative transfer       ////
////       © Astronomical Observatory, Ghent University         ////
///////////////////////////////////////////////////////////////// */

#ifndef GRIDWAVELENGTHDISTRIBUTION_HPP
#define GRIDWAVELENGTHDISTRIBUTION_HPP

#include "DisjointWavelengthGrid.hpp"
#include "WavelengthDistribution.hpp"

////////////////////////////////////////////////////////////////////

/** GridWavelengthDistribution is an abstract class for representing wavelength probability
    distributions derived from a wavelength grid that can be configured by the user. The
    distribution uses only the bins of the configured grid for which the characteristic wavelength
    falls inside the wavelength range of the associated source (obtained through the
    SourceWavelengthRangeInterface), and those bins are selected with equal probability. If none of
    the characteristic wavelengths fall inside the source range, a fatal error is issued.

    Each subclass determines how an actual wavelength is drawn from within a selected bin (see the
    wavelengthInBin() function); this abstract class handles everything else, including a
    probability() function that treats the generated wavelengths as if they were spread out evenly
    over each selected bin, regardless of the precise recipe used by the subclass to place a
    wavelength inside the bin. */
class GridWavelengthDistribution : public WavelengthDistribution
{
    ITEM_ABSTRACT(GridWavelengthDistribution, WavelengthDistribution,
                  "a wavelength probability distribution derived from a wavelength grid")

        PROPERTY_ITEM(wavelengthGrid, DisjointWavelengthGrid, "the wavelength grid defining the distribution")
        ATTRIBUTE_DEFAULT_VALUE(wavelengthGrid, "FileWavelengthGrid")

    ITEM_END()

    //============= Construction - Setup - Destruction =============

protected:
    /** This function determines the grid bins that fall inside the source range. */
    void setupSelfAfter() override;

    //======================== Other Functions =======================

protected:
    /** This function must be implemented in each subclass to return a wavelength inside the bin
        with index \em ell of the configured wavelength grid. */
    virtual double wavelengthInBin(int ell) const = 0;

public:
    /** This function returns the probability of the distribution at the given wavelength. It acts
        as if the wavelengths generated by the generateWavelength() function were spread out over
        each bin (rather than being concentrated into a single wavelength). The returned
        probability is zero for wavelengths outside of the (in-range) bins of the configured
        wavelength grid. For a wavelength that falls inside bin \f$\ell\f$, the returned
        probability is given by \f$ p_\ell = 1 / (\Delta\lambda_\ell \, N_\text{bins}) \f$, where
        \f$\Delta\lambda_\ell\f$ is the width of the bin and \f$N_\text{bins}\f$ is the number of
        (in-range) bins. This value is inversely proportional to the bin width, and satisfies the
        normalization condition \f$\sum_\ell p_\ell = 1\f$. */
    double probability(double wavelength) const override;

    /** This function draws a random wavelength from the wavelength distribution. It first selects
        one of the (in-range) bins of the configured grid with equal probability, and then calls
        wavelengthInBin() to obtain the actual wavelength within that bin. */
    double generateWavelength() const override;

    //======================== Data Members ========================

private:
    // data members initialized during setup
    int _beginWavelengthIndex{0};
    int _endWavelengthIndex{0};
    int _numWavelengths{0};
};

////////////////////////////////////////////////////////////////////

#endif
