/*//////////////////////////////////////////////////////////////////
////     The SKIRT project -- advanced radiative transfer       ////
////       © Astronomical Observatory, Ghent University         ////
///////////////////////////////////////////////////////////////// */

#include "DonutGeometry.hpp"
#include "FatalError.hpp"
#include "Quadrics.hpp"
#include "Random.hpp"

//////////////////////////////////////////////////////////////////////

void DonutGeometry::setupSelfBefore()
{
    AxGeometry::setupSelfBefore();

    // verify property values
    if (_r0 > _R0)
        throw FATALERROR(
            "The radius in the equatorial plane should not be smaller than the radius in the azimuthal plane");

    // determine the normalization factor
    _A = 0.5 / M_PI / M_PI / _r0 / _r0 / _R0;

    // store the small circle radius squared
    _r02 = _r0 * _r0;

    // tabulate the cumulative distribution of the marginal radial probability density
    // p(R) dR \propto R * sqrt(r0^2 - (R-R0)^2) dR for R0-r0 <= R <= R0+r0, so that a random
    // radius can be generated by numerical inversion (through linear interpolation) rather than
    // by rejection sampling; this integral does not have a closed-form inverse because the
    // antiderivative of the radial kernel mixes an arcsine term with algebraic terms in R
    int N = 1000;
    double Rmin = _R0 - _r0;
    double Rmax = _R0 + _r0;
    double dR = (Rmax - Rmin) / N;
    _Rv.resize(N + 1);
    _Xv.resize(N + 1);
    for (int i = 0; i <= N; i++) _Rv[i] = Rmin + i * dR;
    _Xv[0] = 0.0;
    double intprev = 0.0;
    for (int i = 1; i <= N; i++)
    {
        double intR = _Rv[i] * Quadrics::sqrtDiffSquares(_r0, _Rv[i] - _R0);
        _Xv[i] = _Xv[i - 1] + 0.5 * dR * (intprev + intR);
        intprev = intR;
    }
    _Xv /= _Xv[N];
}

//////////////////////////////////////////////////////////////////////

double DonutGeometry::density(double R, double z) const
{
    // calculate the distance squared from the small circle centre
    double d2 = (_R0 - R) * (_R0 - R) + z * z;

    // the density is zero outside the ring torus geometry
    if (d2 >= _r02) return 0.0;

    // the density is uniform inside the ring torus geometry
    else
        return _A;
}

//////////////////////////////////////////////////////////////////////

Position DonutGeometry::generatePosition() const
{
    // generate a random cylindrical radius from the tabulated marginal cumulative distribution
    double R = random()->cdfLinLin(_Rv, _Xv);

    // because the density is uniform inside the torus, z has a uniform conditional distribution
    // given R, over the range set by the torus tube at that radius
    double zmax = Quadrics::sqrtDiffSquares(_r0, R - _R0);
    double z = zmax * (2.0 * random()->uniform() - 1.0);

    // generate a uniform azimuthal angle
    double phi = 2.0 * M_PI * random()->uniform();

    // return position
    return Position(R, phi, z, Position::CoordinateSystem::CYLINDRICAL);
}

//////////////////////////////////////////////////////////////////////

double DonutGeometry::SigmaR() const
{
    return _A * 2 * _r0;
}

//////////////////////////////////////////////////////////////////////

double DonutGeometry::SigmaZ() const
{
    return 0.0;
}

//////////////////////////////////////////////////////////////////////
