# GitHub action workflow for performing automated code formatting check
#
# event trigger (possible options: push, pull_request)
on: [pull_request]
# jobs that run
jobs:
  # automatic formatting check
  autoformat_job:
    # run this job on a Github provided machine running Ubuntu 18.04
    runs-on: ubuntu-latest
    # job name, displayed in the action log
    name: Automatic formatting check
    # steps that make up this job
    steps:
    # checkout using the default checkout, v2
    - name: Checkout
      uses: actions/checkout@v2
    # autoformat
    - name: Autoformat
      # we need this ID to refer to this action later
      id: format
      # the format action has no official releases, so we simply use the
      # latest master branch
      uses: SKIRT/auto-format@master
    # return an error message if code changed by automatic formatting
    - name: Format check
      # this step depends on the status returned by the formatting action
      # we can access this status using the ID we introduced above
      if: steps.format.outputs.status == 'changed'
      # display an error message and return with a non-zero exit code
      # this will make the workflow fail
      run: |
        echo "Code not correctly formatted!"
        exit 1
